### ISSUE TITLE
怎麼沒有人按星星

### ISSUE THREAD

**Issue by 123hi123** [kiraYuukiAsuna/ManSuiAiAssistantUI#1]
這裡下載是直接載整包嗎
還是只能載夸克上的
我夸克載很慢所以問一個

**Comment by kiraYuukiAsuna** [comment]
No, 这里只有代码，需要去网盘或群里下完整的包 ：）

**Comment by 123hi123** [comment]
好 沖起來

**Comment by 123hi123** [comment]
![image](https://github.com/user-attachments/assets/eceda431-4920-41e5-97cf-ef3afdf9a73a)
為啥是有兩個zip啊

**Comment by 123hi123** [comment]
想問一下怎麼加群 有qq wechat
然後就是你解˙壓縮 的程序是甚麼 用windows自帶的沒有辦法
還有夸克上的版本是最新的嗎

**Comment by kiraYuukiAsuna** [comment]
> 想問一下怎麼加群 有qq wechat 然後就是你解˙壓縮 的程序是甚麼 用windows自帶的沒有辦法 還有夸克上的版本是最新的嗎

Sorry! 没注意看消息。
QQ Group: 984069675
